import { AlertCircle, ArrowRight, ArrowUpRight, CheckCircle2, CircleDollarSign, Clock3, FileText, Megaphone, RefreshCw, Sparkles, Users, WalletCards } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AdRequest, Campaign, Client, FacebookOverview, Invoice } from "../../../types/crm";
import { formatDate, formatMoney } from "../../../lib/formatters";
import { Card } from "../../shared/Card";
import { StatusBadge } from "../../shared/StatusBadge";

const formatInvoiceTotals = (invoices: Invoice[], fallbackCurrency = "USD") => {
  const totals = new Map<string, number>();
  invoices.forEach((invoice) => totals.set(invoice.currency, (totals.get(invoice.currency) || 0) + invoice.amount));
  return totals.size
    ? [...totals.entries()].map(([currency, amount]) => formatMoney(amount, currency)).join(" · ")
    : formatMoney(0, fallbackCurrency);
};

const requestTone = (status: AdRequest["status"]) => status === "Rejected" ? "danger" : status === "Live" ? "success" : "warning";
const campaignTone = (status: Campaign["status"]) => status === "active" ? "success" : status === "failed" ? "danger" : "warning";

export function DashboardPage({ clients, requests, campaigns, invoices, facebookOverview }: { clients: Client[]; requests: AdRequest[]; campaigns: Campaign[]; invoices: Invoice[]; facebookOverview: FacebookOverview | null }) {
  const fallbackCurrency = facebookOverview?.overview?.currency || invoices[0]?.currency || campaigns[0]?.budget?.currency || "USD";
  const unpaidInvoices = invoices.filter((item) => item.status !== "Paid");
  const overdueInvoices = invoices.filter((item) => item.status === "Overdue");
  const pendingRequests = requests.filter((item) => !["Live", "Rejected"].includes(item.status));
  const activeCampaigns = campaigns.filter((item) => item.status === "active");
  const activeClients = clients.filter((item) => item.status === "active");
  const staleCampaigns = campaigns.filter((item) => item.isStale || item.status === "failed");
  const sourceLabel = facebookOverview?.source === "facebook-graph-and-stored-data" ? "Facebook Graph API + CRM records" : "CRM records only";
  const trend = campaigns.slice(0, 8).reverse().map((item, index) => ({ name: `C${index + 1}`, spend: item.performance?.spend || 0 }));
  const kpis = [
    { label: "Active campaigns", value: String(activeCampaigns.length), meta: `${campaigns.length} total campaigns`, icon: Megaphone, tone: "text-emerald-300 bg-emerald-400/10", href: "/campaigns" },
    { label: "Pending approvals", value: String(pendingRequests.length), meta: pendingRequests.length ? "Needs your review" : "Queue is clear", icon: FileText, tone: "text-amber-300 bg-amber-400/10", href: "/requests" },
    { label: "Outstanding balance", value: formatInvoiceTotals(unpaidInvoices, fallbackCurrency), meta: `${overdueInvoices.length} overdue invoices`, icon: WalletCards, tone: "text-rose-300 bg-rose-400/10", href: "/billing" },
    { label: "Active clients", value: String(activeClients.length), meta: `${clients.length} client records`, icon: Users, tone: "text-blue-300 bg-blue-400/10", href: "/clients" },
  ];

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-2xl border border-blue-400/15 bg-[radial-gradient(circle_at_top_right,_rgba(59,130,246,0.22),_transparent_38%),linear-gradient(135deg,#111827,#0d1422)] p-5 shadow-xl shadow-blue-950/10 sm:p-7">
      <div className="relative z-10 max-w-2xl"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-blue-300/20 bg-blue-300/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-blue-200"><Sparkles className="size-3.5" />Operations overview</div><h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">Make the next best move for your agency.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">Your workspace at a glance: review approvals, watch campaign health, and stay ahead of client and billing follow-ups.</p><div className="mt-5 flex flex-wrap gap-2"><a href="/requests" className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-blue-500 px-4 text-sm font-semibold text-white shadow-lg shadow-blue-950/30 transition hover:bg-blue-400">Review requests<ArrowRight className="size-4" /></a><a href="/campaigns" className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 text-sm font-semibold text-slate-200 transition hover:bg-white/10">View campaign health</a></div></div><div className="pointer-events-none absolute -right-10 -top-20 size-64 rounded-full border border-blue-300/10 bg-blue-400/5 blur-[1px]" /></section>

    <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(({ label, value, meta, icon: Icon, tone, href }) => <a href={href} key={label} className="group"><Card className="h-full p-4 transition duration-200 group-hover:-translate-y-0.5 group-hover:border-blue-400/30 group-hover:bg-[#151d2d]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 break-words text-2xl font-bold leading-tight text-slate-100">{value}</p></div><div className={`shrink-0 rounded-xl p-2.5 ${tone}`}><Icon className="size-4" /></div></div><p className="mt-4 flex items-center justify-between gap-2 text-xs text-slate-500"><span>{meta}</span><ArrowUpRight className="size-3.5 transition group-hover:text-blue-300" /></p></Card></a>)}</section>

    <section className="grid gap-5 xl:grid-cols-[1.55fr_1fr]">
      <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#20293a] p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-slate-100">Needs attention</h3><span className="rounded-full bg-amber-400/10 px-2 py-0.5 text-[10px] font-semibold text-amber-200">{pendingRequests.length + overdueInvoices.length + staleCampaigns.length} items</span></div><p className="mt-1 text-xs text-slate-500">Prioritized follow-ups across your workspace</p></div><a href="/updates" className="text-xs font-semibold text-blue-300 hover:text-blue-200">Open updates <ArrowRight className="ml-1 inline size-3" /></a></div><div className="divide-y divide-[#20293a]">{pendingRequests.slice(0, 3).map((item) => <a href="/requests" key={item._id} className="flex items-center gap-3 p-4 transition hover:bg-white/[0.025]"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-amber-400/10 text-amber-300"><Clock3 className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{item.requestNumber} · {item.pageName}</p><p className="mt-1 truncate text-xs text-slate-500">{item.client?.name || "Unassigned client"} · {item.objective}</p></div><StatusBadge tone={requestTone(item.status)}>{item.status}</StatusBadge></a>)}{overdueInvoices.slice(0, 2).map((item) => <a href="/billing" key={item._id} className="flex items-center gap-3 p-4 transition hover:bg-white/[0.025]"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-rose-400/10 text-rose-300"><CircleDollarSign className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{item.invoiceNumber} · {item.client?.name || item.pageName}</p><p className="mt-1 text-xs text-slate-500">Payment follow-up required</p></div><span className="text-sm font-semibold text-rose-200">{formatMoney(item.amount, item.currency)}</span></a>)}{staleCampaigns.slice(0, 2).map((item) => <a href="/campaigns" key={item._id} className="flex items-center gap-3 p-4 transition hover:bg-white/[0.025]"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-red-400/10 text-red-300"><RefreshCw className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.isStale ? "Sync is stale" : "Campaign delivery failed"}</p></div><StatusBadge tone={campaignTone(item.status)}>{item.status}</StatusBadge></a>)}{!pendingRequests.length && !overdueInvoices.length && !staleCampaigns.length && <div className="flex items-center gap-3 p-7 text-sm text-slate-400"><CheckCircle2 className="size-5 text-emerald-300" />Everything is under control right now.</div>}</div></Card>

      <Card className="p-4"><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold text-slate-100">Campaign spend</h3><p className="mt-1 text-xs text-slate-500">Spend across current CRM campaigns</p></div><span className="rounded-full border border-[#263044] bg-[#0a0e17] px-2.5 py-1 text-[10px] font-semibold text-slate-400">{fallbackCurrency}</span></div>{trend.length ? <div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ left: -20, right: 8 }}><defs><linearGradient id="spendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#60a5fa" stopOpacity={0.38}/><stop offset="100%" stopColor="#60a5fa" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#20293a" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: "#0a0e17", border: "1px solid #263044", borderRadius: 10, fontSize: 12 }} /><Area type="monotone" dataKey="spend" stroke="#60a5fa" strokeWidth={2.5} fill="url(#spendFill)" /></AreaChart></ResponsiveContainer></div> : <div className="crm-empty mt-4 h-52"><Megaphone className="size-5" />Campaign spend will appear here.</div>}<div className="mt-4 flex items-center justify-between border-t border-[#20293a] pt-3 text-xs"><span className="text-slate-500">Facebook source</span><span className="font-semibold uppercase tracking-wide text-slate-400">{sourceLabel}</span></div></Card>
    </section>

    <section className="grid gap-5 xl:grid-cols-[1.3fr_1fr]">
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[#20293a] p-4"><div><h3 className="text-sm font-semibold text-slate-100">Client pulse</h3><p className="mt-1 text-xs text-slate-500">Active clients with the most live activity</p></div><a href="/clients" className="text-xs font-semibold text-blue-300 hover:text-blue-200">View clients <ArrowRight className="ml-1 inline size-3" /></a></div><div className="grid gap-2 p-3 sm:grid-cols-2">{activeClients.slice(0, 6).map((client) => <a href="/clients" key={client._id} className="rounded-xl border border-[#20293a] bg-[#0c1220] p-3 transition hover:border-blue-400/30 hover:bg-[#111a2a]"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full text-xs font-bold text-white" style={{ backgroundColor: client.color || "#2563eb" }}>{client.name.slice(0, 2).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-200">{client.name}</p><p className="truncate text-xs text-slate-500">{client.activeCampaigns} active campaigns</p></div></div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-slate-500">Spend to date</span><span className="font-semibold text-slate-300">{formatMoney(client.totalSpend, fallbackCurrency)}</span></div></a>)}{!activeClients.length && <div className="crm-empty sm:col-span-2"><Users className="size-5" />Active client data will appear here.</div>}</div></Card>

      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[#20293a] p-4"><div><h3 className="text-sm font-semibold text-slate-100">Recent requests</h3><p className="mt-1 text-xs text-slate-500">Latest work entering the pipeline</p></div><a href="/requests" className="text-xs font-semibold text-blue-300 hover:text-blue-200">View queue <ArrowRight className="ml-1 inline size-3" /></a></div>{requests.length ? <div className="divide-y divide-[#20293a]">{requests.slice(0, 4).map((item) => <a href="/requests" key={item._id} className="flex items-center gap-3 p-4 transition hover:bg-white/[0.025]"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{item.requestNumber}</p><p className="mt-1 truncate text-xs text-slate-500">{item.client?.name || item.pageName}</p></div><div className="text-right"><StatusBadge tone={requestTone(item.status)}>{item.status}</StatusBadge><p className="mt-1 text-[10px] text-slate-600">{formatDate(item.createdAt)}</p></div></a>)}</div> : <div className="crm-empty"><FileText className="size-5" />No requests have been submitted.</div>}</Card>
    </section>
  </div>;
}
