import { AlertCircle, ArrowUpRight, CircleDollarSign, FileText, Megaphone, MousePointerClick, Radio, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AdRequest, Campaign, Client, FacebookOverview, Invoice, Role } from "../../../types/crm";
import { formatDate, formatMoney } from "../../../lib/formatters";
import { Card } from "../../shared/Card";
import { StatusBadge } from "../../shared/StatusBadge";

const chartTooltip = { backgroundColor: "#111827", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12, color: "#e2e8f0", fontSize: 12 };

export function DashboardPage({ clients, requests, campaigns, invoices, facebookOverview, role }: { clients: Client[]; requests: AdRequest[]; campaigns: Campaign[]; invoices: Invoice[]; facebookOverview: FacebookOverview | null; role: Role }) {
  const moderator = role === "moderator";
  const activeCampaigns = campaigns.filter((item) => item.status === "active").length;
  const reviewCount = requests.filter((item) => item.status === "Under Review").length;
  const campaignSpend = campaigns.reduce((sum, item) => sum + (item.performance?.spend || 0), 0);
  const currency = facebookOverview?.overview.currency || campaigns.find((item) => item.budget?.currency)?.budget.currency || "USD";
  const totalSpend = facebookOverview?.overview.spend ?? campaignSpend;
  const totalResults = facebookOverview?.overview.results ?? campaigns.reduce((sum, item) => sum + (item.performance?.results || 0), 0);
  const totalImpressions = facebookOverview?.overview.impressions ?? campaigns.reduce((sum, item) => sum + (item.performance?.impressions || 0), 0);
  const totalReach = campaigns.reduce((sum, item) => sum + (item.performance?.reach || 0), 0);
  const cpa = facebookOverview?.overview.cpa || (totalResults ? totalSpend / totalResults : 0);
  const outstanding = invoices.filter((item) => item.status !== "Paid").reduce((sum, item) => sum + item.amount, 0);

  const spendTrend = (facebookOverview?.recentCampaigns.length ? facebookOverview.recentCampaigns : campaigns).slice(0, 8).reverse().map((item) => ({
    name: item.name.length > 14 ? `${item.name.slice(0, 12)}…` : item.name,
    spend: "performance" in item ? item.performance.spend : item.spend,
    results: "performance" in item ? item.performance.results : item.results,
  }));
  const performanceData = [
    { name: "Impressions", value: totalImpressions, color: "#3b82f6" },
    { name: "Reach", value: totalReach, color: "#6366f1" },
    { name: "Results", value: totalResults, color: "#22c55e" },
  ];
  const stats = [
    { label: "Total ad spend", value: formatMoney(totalSpend, currency), icon: CircleDollarSign, meta: `${activeCampaigns} campaigns live`, accent: "from-blue-500/20 to-blue-500/0", color: "text-blue-400" },
    { label: "Active campaigns", value: String(activeCampaigns), icon: Megaphone, meta: `${campaigns.length} campaigns total`, accent: "from-indigo-500/20 to-indigo-500/0", color: "text-indigo-400" },
    { label: "Results generated", value: totalResults.toLocaleString(), icon: MousePointerClick, meta: cpa ? `${formatMoney(cpa, currency)} cost / result` : "Performance pending", accent: "from-emerald-500/20 to-emerald-500/0", color: "text-emerald-400" },
    { label: moderator ? "Access level" : "Active clients", value: moderator ? "Scoped" : String(clients.filter((item) => item.status === "active").length), icon: Users, meta: moderator ? "Moderator workspace view" : `${clients.length} clients managed`, accent: "from-violet-500/20 to-violet-500/0", color: "text-violet-400" },
  ];

  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-[10px] font-bold uppercase tracking-[0.18em] text-blue-400">Command center</p><h2 className="crm-page-title">Workspace overview</h2><p className="crm-page-subtitle">Live operational and campaign performance across your agency</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]" />Data synced from your workspace</div></div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon, meta, accent, color }) => <Card key={label} className="relative p-5"><div className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${accent}`} /><div className="relative flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold tracking-tight text-white">{value}</p><p className="mt-2 flex items-center gap-1 text-xs text-slate-500"><ArrowUpRight className={`size-3.5 ${color}`} />{meta}</p></div><div className={`flex size-10 items-center justify-center rounded-xl border border-white/[0.08] bg-black/20 ${color}`}><Icon className="size-5" /></div></div></Card>)}</div>

    <div className="grid gap-4 xl:grid-cols-[1.6fr_1fr]">
      <Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><h3 className="font-semibold text-white">Spend performance</h3><p className="mt-1 text-xs text-slate-500">Real spend from recent campaigns</p></div><StatusBadge tone="success">Live data</StatusBadge></div><div className="mt-6 h-72">{spendTrend.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={spendTrend} margin={{ left: 0, right: 4, top: 8, bottom: 0 }}><defs><linearGradient id="spendGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3b82f6" stopOpacity={0.38}/><stop offset="100%" stopColor="#3b82f6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.08)" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#64748b", fontSize: 10 }} interval="preserveStartEnd"/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#64748b", fontSize: 10 }} width={42}/><Tooltip contentStyle={chartTooltip} formatter={(value: number) => formatMoney(value, currency)}/><Area type="monotone" dataKey="spend" stroke="#60a5fa" strokeWidth={2.5} fill="url(#spendGradient)" activeDot={{ r: 5, fill: "#60a5fa", stroke: "#111827", strokeWidth: 3 }}/></AreaChart></ResponsiveContainer> : <div className="crm-empty h-full min-h-0">Campaign spend appears here after sync.</div>}</div></Card>
      <Card className="p-5 sm:p-6"><div><h3 className="font-semibold text-white">Performance funnel</h3><p className="mt-1 text-xs text-slate-500">Audience to measurable results</p></div><div className="mt-6 h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={performanceData} layout="vertical" margin={{ left: 4, right: 20 }}><CartesianGrid stroke="rgba(148,163,184,.07)" horizontal={false}/><XAxis type="number" hide/><YAxis type="category" dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} width={76}/><Tooltip contentStyle={chartTooltip} formatter={(value: number) => value.toLocaleString()}/><Bar dataKey="value" radius={[0, 8, 8, 0]} barSize={22}>{performanceData.map((entry) => <Cell key={entry.name} fill={entry.color}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-white/[0.07] pt-4"><div><p className="text-[10px] uppercase tracking-wider text-slate-600">Cost / result</p><p className="mt-1 font-semibold text-white">{cpa ? formatMoney(cpa, currency) : "—"}</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-600">Under review</p><p className="mt-1 font-semibold text-white">{reviewCount}</p></div></div></Card>
    </div>

    <div className="grid gap-4 xl:grid-cols-[1.6fr_1fr]">
      <Card><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><h3 className="font-semibold text-white">Recent requests</h3><p className="mt-0.5 text-xs text-slate-500">Latest campaign approval activity</p></div><FileText className="size-4 text-blue-400" /></div>{requests.length ? <><div className="divide-y divide-white/[0.06] md:hidden">{requests.slice(0, 5).map((item) => <div key={item._id} className="p-4"><div className="flex items-center justify-between gap-2"><span className="font-mono text-xs text-blue-400">{item.requestNumber}</span><StatusBadge tone={item.status === "Live" ? "success" : item.status === "Rejected" ? "danger" : "warning"}>{item.status}</StatusBadge></div><p className="mt-2 font-medium text-slate-200">{item.pageName}</p><p className="mt-1 text-xs text-slate-500">{item.client?.name || "Client"} · {item.objective}</p></div>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[650px]"><thead className="crm-table-head"><tr><th className="px-5 py-3">Request</th><th className="px-5 py-3">Client / Page</th><th className="px-5 py-3">Objective</th><th className="px-5 py-3">Submitted</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{requests.slice(0, 5).map((item) => <tr key={item._id} className="hover:bg-white/[0.02]"><td className="crm-table-cell font-mono text-blue-400">{item.requestNumber}</td><td className="crm-table-cell"><p className="font-medium text-slate-200">{item.pageName}</p><p className="text-xs text-slate-500">{item.client?.name || "—"}</p></td><td className="crm-table-cell">{item.objective}</td><td className="crm-table-cell text-xs text-slate-500">{formatDate(item.createdAt)}</td><td className="crm-table-cell"><StatusBadge tone={item.status === "Live" ? "success" : item.status === "Rejected" ? "danger" : "warning"}>{item.status}</StatusBadge></td></tr>)}</tbody></table></div></> : <div className="crm-empty"><FileText className="size-5"/>No requests have been submitted.</div>}</Card>
      <Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Radio className="size-4 text-blue-400"/><h3 className="font-semibold text-white">Meta connection</h3></div><p className="mt-1 text-xs text-slate-500">Graph API workspace status</p></div><StatusBadge tone={facebookOverview?.connection.isConnected ? "success" : "danger"}>{facebookOverview?.connection.status ?? "unavailable"}</StatusBadge></div><div className="mt-6 grid grid-cols-2 gap-3">{[["Ad accounts", facebookOverview?.connection.accountCount ?? 0], ["Campaigns", facebookOverview?.overview.campaignCount ?? campaigns.length], ["Results", totalResults.toLocaleString()], ["Outstanding", moderator ? "Restricted" : formatMoney(outstanding, invoices[0]?.currency || currency)]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1.5 truncate text-sm font-semibold text-slate-200">{value}</p></div>)}</div>{!facebookOverview && <p className="mt-4 flex items-center gap-2 rounded-xl border border-amber-400/15 bg-amber-400/5 p-3 text-xs text-amber-300"><AlertCircle className="size-4"/>Meta metrics are currently unavailable</p>}{facebookOverview?.connection.lastSyncAt && <p className="mt-4 text-[10px] text-slate-600">Last synced {formatDate(facebookOverview.connection.lastSyncAt)}</p>}</Card>
    </div>
  </div>;
}
