import { useMemo, useState, type FormEvent } from "react";
import { Edit2, Plus, Search, Trash2, Users } from "lucide-react";
import type { Client } from "../../../types/crm";
import { formatMoney } from "../../../lib/formatters";
import { Card } from "../../shared/Card";
import { StatusBadge } from "../../shared/StatusBadge";
import { Button } from "../../shared/Button";

type FormState = { name: string; contactName: string; email: string; facebookPageName: string; adAccountId: string; monthlyBudget: string; billingRate: string; status: Client["status"] };
const blank: FormState = { name: "", contactName: "", email: "", facebookPageName: "", adAccountId: "", monthlyBudget: "500", billingRate: "110", status: "active" };

export function ClientsPage({ clients, onCreateClient, onUpdateClient, onDeleteClient }: { clients: Client[]; onCreateClient: (payload: Omit<Client, "_id">) => Promise<void>; onUpdateClient: (id: string, payload: Partial<Client>) => Promise<void>; onDeleteClient: (id: string) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Client | null>(null); const [form, setForm] = useState<FormState>(blank); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all");
  const filtered = useMemo(() => clients.filter((item) => (!search.trim() || [item.name,item.contactName,item.email,item.facebookPageName,item.adAccountId].some((value)=>value?.toLowerCase().includes(search.toLowerCase()))) && (status === "all" || item.status === status)), [clients, search, status]);
  const startCreate = () => { setEditing(null); setForm(blank); setError(""); setOpen(true); };
  const startEdit = (item: Client) => { setEditing(item); setForm({ name:item.name, contactName:item.contactName, email:item.email, facebookPageName:item.facebookPageName, adAccountId:item.adAccountId, monthlyBudget:String(item.monthlyBudget), billingRate:String(item.billingRate), status:item.status }); setError(""); setOpen(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const payload = { ...form, monthlyBudget:Number(form.monthlyBudget), billingRate:Number(form.billingRate) }; try { if (editing) await onUpdateClient(editing._id, payload); else await onCreateClient({ ...payload, totalSpend:0, activeCampaigns:0, color:"bg-blue-600" }); setOpen(false); } catch (err) { setError(err instanceof Error ? err.message : "Could not save client"); } finally { setSaving(false); } };
  const remove = async (item: Client) => { if (!window.confirm(`Delete ${item.name}?`)) return; try { await onDeleteClient(item._id); } catch (err) { setError(err instanceof Error ? err.message : "Could not delete client"); } };
  return <div className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-100">Client management</h2><p className="text-sm text-slate-500">Accounts, budgets, and Facebook connections</p></div><Button onClick={startCreate}><Plus className="size-4" />Add Client</Button></div>
    {error && !open && <div role="alert" className="rounded-md border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-400">{error}</div>}
    <Card><div className="grid gap-2 border-b border-[#20293a] p-3 sm:grid-cols-[1fr_180px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-600"/><input aria-label="Search clients" className="crm-input pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search clients..."/></div><select className="crm-input" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="paused">Paused</option><option value="onboarding">Onboarding</option></select><span className="self-center text-xs text-slate-500">{filtered.length} records</span></div>{filtered.length ? <div className="crm-responsive-table overflow-x-auto"><table className="w-full"><thead className="crm-table-head"><tr><th className="px-4 py-3">Client</th><th className="px-4 py-3">Facebook</th><th className="px-4 py-3">Budget</th><th className="px-4 py-3">Campaigns</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{filtered.map((item)=><tr key={item._id} className="hover:bg-white/[0.02]"><td className="crm-table-cell"><p className="font-semibold text-slate-200">{item.name}</p><p className="text-xs text-slate-500">{item.contactName} · {item.email}</p></td><td className="crm-table-cell"><p>{item.facebookPageName || "—"}</p><p className="font-mono text-xs text-slate-500">{item.adAccountId || "Not connected"}</p></td><td className="crm-table-cell font-semibold text-slate-200">{formatMoney(item.monthlyBudget)}</td><td className="crm-table-cell">{item.activeCampaigns}</td><td className="crm-table-cell"><StatusBadge tone={item.status === "active" ? "success" : item.status === "paused" ? "warning" : "default"}>{item.status}</StatusBadge></td><td className="crm-table-cell"><div className="flex justify-end gap-2"><button className="crm-icon-button" onClick={()=>startEdit(item)} aria-label={`Edit ${item.name}`} title="Edit client"><Edit2 className="size-3.5"/></button><button className="crm-icon-button hover:border-red-500/40 hover:text-red-400" onClick={()=>remove(item)} aria-label={`Delete ${item.name}`} title="Delete client"><Trash2 className="size-3.5"/></button></div></td></tr>)}</tbody></table></div> : <div className="crm-empty"><Users className="size-5"/>No clients match the current filters.</div>}</Card>
    {open && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget)setOpen(false)}}><Card className="w-full max-w-2xl"><div className="border-b border-[#20293a] px-5 py-4"><h3 className="font-semibold">{editing ? "Edit client" : "Add client"}</h3></div><form onSubmit={submit} className="grid gap-4 p-5 sm:grid-cols-2">{error && <div role="alert" className="sm:col-span-2 rounded-md border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-400">{error}</div>}{([["name","Business name"],["contactName","Contact name"],["email","Email"],["facebookPageName","Facebook page"],["adAccountId","Ad account ID"],["monthlyBudget","Monthly budget"],["billingRate","Billing rate"]] as Array<[keyof FormState,string]>).map(([key,label])=><label key={key}><span className="crm-label">{label}</span><input required={["name","contactName","email"].includes(key)} type={key==="email"?"email":["monthlyBudget","billingRate"].includes(key)?"number":"text"} className="crm-input" value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></label>)}<label><span className="crm-label">Status</span><select className="crm-input" value={form.status} onChange={(e)=>setForm({...form,status:e.target.value as Client["status"]})}><option value="active">Active</option><option value="paused">Paused</option><option value="onboarding">Onboarding</option></select></label><div className="flex justify-end gap-2 border-t border-[#20293a] pt-4 sm:col-span-2"><button type="button" className="rounded-md border border-[#263044] px-4 py-2 text-sm text-slate-300" onClick={()=>setOpen(false)}>Cancel</button><Button disabled={saving}>{saving?"Saving...":"Save Client"}</Button></div></form></Card></div>}
  </div>;
}
