import { Router } from "express";
import { createAdRequest, getAdRequests, updateAdRequestStatus } from "../controllers/adRequest.controller.js";
import { validateAdRequestCreate, validateAdRequestStatus } from "../validators/adRequest.validator.js";
import { agencyScopeMiddleware } from "../middlewares/agencyScope.middleware.js";
import { roleMiddleware } from "../middlewares/role.middleware.js";
import { validateObjectIdParam } from "../validators/common.validator.js";
const router = Router({ mergeParams: true });
router.param("requestId", validateObjectIdParam);
router.use("/:agencyId", agencyScopeMiddleware);
router.get("/:agencyId", getAdRequests);
router.post("/:agencyId", validateAdRequestCreate, createAdRequest);
router.patch("/:agencyId/:requestId/status", roleMiddleware("admin", "team"), validateAdRequestStatus, updateAdRequestStatus);
export default router;
